Controllers/BasesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SIIGMA.Models;
using SIIGMA.Constants;
using SIIGMA.DTO;
using SIIGMA.Services;
using System.Linq.Dynamic;
using System.Text;
using System.Diagnostics;
using System.Threading.Tasks;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Validation;
using System.IO;
using System.Data;
using System.Data.OleDb;
using System.ComponentModel;
using NPOI.HSSF.UserModel;
using NPOI.SS.UserModel;
using NPOI.XSSF.UserModel;

namespace SIIGMA.Controllers
{
    [RoutePrefix("bases")]
    public class BasesController : Controller
    {
        #region Fields
        private readonly ILoggingService _logginService;
        #endregion

        #region Constructors
        public BasesController(ILoggingService logginService) {
            this._logginService = logginService;
        }
        #endregion

        [Route("listarproductos", Name = BasesControllerRoute.ListarProductos)]
        public JsonResult ListarProductos([Bind(Include = "sidx,sord,page,rows,documento,searchField,searchString,searchOper")]ListarProductosDTO model)
        {

            if(model == null || !ModelState.IsValid)
                return Json(new { total = 0, model.page, records = 0, rows = "" }, JsonRequestBehavior.AllowGet);
            if(string.IsNullOrEmpty(model.documento))
                return Json(new { total = 0, model.page, records = 0, rows = "" }, JsonRequestBehavior.AllowGet);

            int index = model.page - 1;
            int size = model.rows;

            Context_DBSegban _db = new Context_DBSegban();
            if(string.IsNullOrEmpty(model.searchField) || string.IsNullOrEmpty(model.searchstring))
            {
                var list = _db.TblInfoProducto.Where(q => q.ID_CLIENTE.Equals(model.documento));
                int totalreg = list.Count();
                int pages = (int)Math.Ceiling((float) totalreg / (float) model.rows);
                list = list.OrderBy(string.Format("{0} {1}", model.sidx, model.sord));

                list = list.Skip(index * size).Take(size);
                return Json(new { total = pages, model.page, records = totalreg, rows = list }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                StringBuilder query = new StringBuilder("SELECT * FROM [GESTION_DEBITO].[Tbl_Informacion_Producto] WHERE ID_CLIENTE = @p0").Append(construirCondicion(model.searchField, model.searchOper));
                IQueryable<InfoProducto> list = new List<InfoProducto>().AsQueryable();
                try
                {
                    list = _db.Database.SqlQuery<InfoProducto>(query.ToString(), model.documento, model.searchstring).AsQueryable();
                }
                catch(Exception e)
                {
                    Debug.WriteLine(e.Message);
                }

                int totalreg = list.Count();
                int pages = (int) System.Math.Ceiling((float) totalreg / (float) model.rows);
                list = list.OrderBy(string.Format("{0} {1}", model.sidx, model.sord));

                list = list.Skip(index * size).Take(size);
                return Json(new { total = pages, model.page, records = totalreg, rows = list }, JsonRequestBehavior.AllowGet);
            }
        }

        [Route("jqgriddispatcher", Name = BasesControllerRoute.JqGridDispatcher)]
        public JsonResult JqGridDataDispatcher([Bind(Include = "sender,sidx,sord,page,rows,documento,producto,prod_numero,cuenta_numero,searchField,searchString,searchOper")]JqGridDataDispatcherDTO model)
        {
            model.searchField = string.Empty;
            model.searchOper = string.Empty;
            model.searchstring = string.Empty;

            int index = model.page - 1;
            int size = model.rows;

            IQueryable<dynamic> list = Enumerable.Empty<dynamic>().AsQueryable();
            Context_DBSegban _db = new Context_DBSegban();
            switch(model.sender)
            {
                case ".gr-trx":
                    list = _db.TblInfoTransaccion.Where(q => q.ID_CLIENTE.Equals(model.documento) &&
                        q.TIPO_PRODUCTO.Equals(model.producto) && q.NUMERO_PRODUCTO.Equals(model.prod_numero) && q.NUMERO_CUENTA.Equals(model.cuenta_numero));
                    break;
                case ".gr-novedad":
                    list = _db.TblNovedadTransaccion.Where(q => q.ID_CLIENTE.Equals(model.documento) &&
                        q.TIPO_PRODUCTO.Equals(model.producto) && q.NUMERO_PRODUCTO.Equals(model.prod_numero) && q.NUMERO_CUENTA.Equals(model.cuenta_numero));
                    break;
                case ".gr-fraude":
                    list = _db.TblMarcacionFraude.Where(q => q.ID_CLIENTE.Equals(model.documento) &&
                        q.TIPO_PRODUCTO.Equals(model.producto) && q.NUMERO_PRODUCTO.Equals(model.prod_numero) && q.NUMERO_CUENTA.Equals(model.cuenta_numero));
                    break;
                default:
                    break;
            }

            int totalreg = list.Count();
            int pages = (int) Math.Ceiling(totalreg / (float) model.rows);
            list = list.OrderBy(string.Format("{0} {1}", model.sidx, model.sord));
            list = list.Skip(index * size).Take(size);

            return Json(new { total = pages, model.page, records = totalreg, rows = list }, JsonRequestBehavior.AllowGet);
        }

        [Route("_makedropdown", Name = BasesControllerRoute.MakeDropdown)]
        public async Task<ActionResult> _MakeDropdown(string t)
        {
            if(string.IsNullOrEmpty(t))
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);

            Dictionary<string, string> list = new Dictionary<string, string>();
            Context_DBSegban _db = new Context_DBSegban();
            switch(t.ToLower())
            {
                case "t_bloqueo":
                    var bloqs = _db.TblTipoBloqueo;
                    foreach(var b in bloqs)
                        list.Add(b.GESTION, b.GESTION);
                    break;
                case "t_prod":
                    var prods = _db.TblProducto;
                    foreach(var p in prods)
                        list.Add(p.TIPO_PRODUCTO, p.TIPO_PRODUCTO);
                    break;
                case "t_estadotxa":
                    var est = _db.TblEstadoTransaccion;
                    foreach(var e in est)
                        list.Add(e.MARCACION_TXA, e.MARCACION_TXA);
                    break;
                case "t_canaltxa":
                    var canales = _db.TblCanal;
                    foreach(var c in canales)
                        list.Add(c.CANAL, c.NOMBRE_CANAL);
                    break;
                case "t_tipotxa":
                    var tipos = _db.TblTipoTransaccion;
                    foreach(var tp in tipos)
                        list.Add(tp.TIPO_TRANSACCION, tp.TIPO_TRANSACCION);
                    break;
                case "t_ciudadtxa":
                    var ciudades = _db.TblCiudad.OrderBy("depto ASC, ciudad ASC");
                    foreach(var cd in ciudades)
                        list.Add(cd.codCiudad.ToString(), string.Format("{0}, {1}", cd.ciudad, cd.depto));
                    break;
                case "t_paistxa":
                    var paises = _db.TblPais;
                    foreach(var pa in paises)
                        list.Add(pa.Codigo_Pais, string.Format("{0}, {1}", pa.Codigo_Pais, pa.NPais));
                    break;
                case "t_resptxa":
                    var resp = _db.TblRespuestaTxa;
                    foreach(var re in resp)
                        list.Add(re.COD_RESPUESTA, string.Format("{0}, {1}", re.COD_RESPUESTA, re.DESCRIPCION_RESPUESTA));
                    break;
                case "t_riesgotxa":
                    var riesgos = _db.TblRiesgoAlerta;
                    foreach(var ri in riesgos)
                        list.Add(ri.RIESGO_ALERTA, ri.RIESGO_ALERTA);
                    break;
                case "t_herrtxa":
                    var herrs = _db.TblHerramientaDeteccion;
                    foreach(var h in herrs)
                        list.Add(h.HERRAMIENTA_DETECCION, h.HERRAMIENTA_DETECCION);
                    break;
                case "t_causadesm":
                    var caus = _db.TblCausasDesmarcacion;
                    foreach(var ca in caus)
                        list.Add(ca.CAUSA_DESMARCACION, ca.CAUSA_DESMARCACION);
                    break;
                case "t_empleado":
                    var emps = _db.TblEmpleado;
                    foreach(var e in emps)
                        list.Add(e.CEDULA, string.Format("{0}, {1}", e.CEDULA, e.NOMBRE));
                    break;
                case "t_oficina":
                    var ofs = _db.TblOficina.OrderBy("DEPARTAMENTO ASC, NOMBRE_OFICINA ASC");
                    foreach(var of in ofs)
                        list.Add(of.CODIGO, string.Format("[{0}] {1}, {2}", of.CODIGO, of.NOMBRE_OFICINA, of.DEPARTAMENTO));
                    break;
                case "t_usuario":
                    var usus = _db.TblUsuario.OrderBy(q => q.USUARIO_BASE);
                    foreach(var u in usus)
                        list.Add(u.USUARIO_RED, string.Format("[{0}], {1} {2}", u.USUARIO_RED, u.NOMBRE, u.APELLIDO));
                    break;
                case "t_modalidad":
                    var mods = _db.TblModalidad;
                    foreach(var mod in mods)
                        list.Add(mod.MODALIDAD, mod.MODALIDAD);
                    break;
                default:
                    break;
            }

            await Task.Delay(TimeSpan.FromSeconds(1));
            ViewBag.Items = list;
            return PartialView();
        }

        [ValidateAntiForgeryToken]

Views/Bases/_BasesGestion.cshtml
<h3><i class="fa fa-database" aria-hidden="true"></i> Bases de Gesti&oacute;n - Seguimiento Transaccional</h3>
<div id="data-div" class="hidden hidden-xs hidden-sm hidden-md hidden-lg hidden-print" data-id-cliente="" data-producto="" data-num-producto="" data-num-cuenta="" data-usuario="@User.Identity.Name.Substring(User.Identity.Name.LastIndexOf('\\') + 1)">
    <form id="__AjaxAntiForgeryForm" action="#" method="post">@Html.AntiForgeryToken()</form>
</div>
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <section>
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <div class="form-horizontal">
                                <label class="control-label col-xs-12 col-sm-4 col-md-4 col-lg-4">Documento cliente</label>
                                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
                                    <input id="txt-doc" type="number" class="form-control" style="max-width: 100%;" placeholder="Documento cliente" />
                                </div>
                                <button type="button" id="btn-buscar-doc" class="btn btn-primary col-xs-12 col-sm-2 col-md-2 col-lg-2"><i class="fa fa-search"></i> Buscar</button>
                            </div>
                        </div>
                    </div>
                </div>
                @if(User.Identity.IsAuthenticated && User.IsInRole("Administrador"))
                {
                    <div class="col-xs-6 col-sm-6 col-md-4 col-lg-4 pull-right">
                        <div class="panel panel-default">
                            <div class="panel-body">
                                <div class="text-center">
                                    <a href="@Url.Action("ExportarExcel", "Bases")" class="btn btn-success"><i class="fa fa-file-excel-o" aria-label="hidden"></i> Consolidado Fraudes (Puntos Compromiso)</a>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>

            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">Detalle Informaci&oacute;n</div>
                        <div class="panel-body">
                            <section>
                                <div class="panel panel-default">
                                    <div class="panel-heading"><span class="text-success"><i class="fa fa-lock" aria-hidden="true"></i> Informaci&oacute;n bloqueos.</span></div>
                                    <table id="grid-bloqueos"></table>
                                    <div id="pager-bloqueos"></div>
                                </div>
                            </section>
                            <section>
                                <div class="panel panel-default">
                                    <div class="panel-heading"><span class="text-primary"><i class="fa fa-credit-card" aria-hidden="true"></i> Informaci&oacute;n transacciones.</span> <div class="pull-right">@using(Ajax.BeginForm("IngresoMasivo", "Bases", new { }, new AjaxOptions { }, new { enctype = "multipart/form-data", id = "frm-cargar" }))
                                    { <label class="btn btn-xs btn-primary btn-file" disabled="disabled" id="lblMasivoTrx"><i class="fa fa-file-excel-o" aria-hidden="true"></i> Seleccionar archivo <input type="file" name="MasivoTrx" id="MasivoTrx" style="display:none" disabled="disabled" /></label> <input type="hidden" name="hidID_CLIENTE" id="hidID_CLIENTE" /> <input type="hidden" name="hidNUMERO_CUENTA" id="hidNUMERO_CUENTA" /> <input type="hidden" name="hidNUMERO_PRODUCTO" id="hidNUMERO_PRODUCTO" /> <input type="hidden" name="hidTIPO_PRODUCTO" id="hidTIPO_PRODUCTO" /><button type="submit" name="btnCargar" id="btnCargar" value="Cargar" class="btn btn-xs btn-success" disabled="disabled" data-loading-text="<i class='fa fa-spinner fa-spin'></i> Cargando transacciones..."><i class="fa fa-upload" aria-hidden="true"></i> Cargar</button> }</div></div>
                                    <table id="grid-trx"></table>
                                    <div id="pager-trx"></div>
                                </div>
                            </section>
                            <section>
                                <div class="panel panel-default">
                                    <div class="panel-heading"><span class="text-success"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Informaci&oacute;n novedades.</span></div>
                                    <table id="grid-novedades"></table>
                                    <div id="pager-novedades"></div>
                                </div>
                            </section>
                            <section>
                                <div class="panel panel-default">
                                    <div class="panel-heading"><span class="text-danger"><i class="fa fa-user" aria-hidden="true"></i> Marcaci&oacute;n fraude.</span></div>
                                    <table id="grid-marcaciones"></table>
                                    <div id="pager-marcaciones"></div>
                                </div>
                            </section>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>

Views/Bases/_MakeDropdown.cshtml
<select>
    @foreach(KeyValuePair<string, string> pair in ViewBag.Items)
    {
        <option value="@pair.Key">@pair.Value</option>
    }
</select>